### ISSUE TITLE
Save weight

### ISSUE THREAD

**Issue by z430** [mari-linhares/tensorflow-maml#1]
Thanks for sharing your code. 
I have a question, how to save the MAML weight? I tried save the MAML object using pickle but didn't work

**Comment by hereismari** [comment]
Hey @z430,

Can you try [`model.save`](https://www.tensorflow.org/tutorials/keras/save_and_restore_models#as_an_hdf5_file)?

This should work out of the box.

**Comment by z430** [comment]
yeah, `model.save_weights` works
